# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-java8:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx1048m
      TERM: dumb
    
    steps:
      - checkout #checks out your code to your working directory
      - restore_cache:
          keys:
            - dependency-cache
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: run checks
          command: ./gradlew check dependencyCheckUpdate dependencyCheckAnalyze --no-daemon
          environment: 
            GRADLE_OPTS: "-Xmx1024m -Dorg.gradle.jvmargs='-Xmx1024m'"
      - run:
          name: upload code coverage
          command: ./gradlew coveralls --no-daemon
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      # Save dependency cache
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.gradle

  build-java11:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx1048m
      TERM: dumb
    
    steps:
      - checkout #checks out your code to your working directory
      - restore_cache:
          keys:
            - dependency-cache
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: run checks
          command: ./gradlew check --no-daemon
          environment: 
            GRADLE_OPTS: "-Xmx1024m -Dorg.gradle.jvmargs='-Xmx1024m'"

  build-java17:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx1048m
      TERM: dumb
    
    steps:
      - checkout #checks out your code to your working directory
      - restore_cache:
          keys:
            - dependency-cache
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: run checks
          command: ./gradlew check --no-daemon
          environment: 
            GRADLE_OPTS: "-Xmx1024m -Dorg.gradle.jvmargs='-Xmx1024m'"

workflows:
  version: 2
  build:
    jobs:
      - build-java8
      - build-java11
      - build-java17